netty:
  port: 8868
netty-server:
  enabled: true
spring:
  datasource:
    url: jdbc:h2:mem:test;INIT=RUNSCRIPT FROM 'classpath:db/data.sql'
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    timeBetweenEvictionRunsMillis: 4000
    validationQuery: SELECT 1
    testWhileIdle: true
    slowSQLMills: 4000
    logSlowSql: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        #解决数据库字段驼峰命名使用@Column注解无法正常解析

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false